version: '3.4'

services:
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Salasana123/
      attach_dbs: '[{"dbName":"MatkaLasku","dbFiles":["/var/opt/mssql/data/MatkaLasku.mdf","/var/opt/mssql/data/MatkaLasku_log.ldf"]}]'
    ports:
      - 1433:1433
    volumes:
      - ./sqldata:/var/opt/mssql/data