version: '3.4'

services:
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Salasana123/
      TZ: Europe/Helsinki
    ports:
      - 1433:1433